### ISSUE TITLE
Implement code coverage for fastapi-example

### ISSUE THREAD

**Issue by redat97** [ai-cfia/fastapi-example#13]

**Comment by redat97** [comment]
test

**Comment by k-allagbe** [comment]
> test

test

**Comment by rngadam** [comment]
Code coverage for Github Actions? Why? Please provide a description to your issues explaining at least why.

**Comment by rngadam** [comment]
Not sure why I have a Github notification for this as if it is a new issue when it dates back to Oct 2nd.

**Comment by redat97** [comment]
> Code coverage for Github Actions? Why? Please provide a description to your issues explaining at least why.

This was created two months ago before I understood that description go into issues and not PRs shouldn't happen again

**Comment by rngadam** [comment]
@redat97 I'm also concerned that this is not associated to any Github Project. We need some visibility on "orphaned" issues.

**Comment by redat97** [comment]
> Not sure why I have a Github notification for this as if it is a new issue when it dates back to Oct 2nd.

weird but no worries then I'll update everything when I get to working on it again

**Comment by redat97** [comment]
The implementation ended up being made inside the lint-test workflow but original plan was to have a separate workflow added to the project but now when the lint-test workflow gets called, it automatically generates a code coverage report
